/*
	-- SCRIPT DE BASE DE DATOS MYSQL 5.7
	-- ARQUITECTURA DE INFORMACIÓN
	-- PROYECTO 4, UNA 2018
	-- GERSON VARGAS & OSVALDO AGUERO
*/

-- ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';
-- SET PASSWORD FOR 'root'@'localhost' = PASSWORD('root');
--  flush privileges;

DROP DATABASE IF EXISTS PHONEBILL;
CREATE DATABASE IF NOT EXISTS PHONEBILL;
USE PHONEBILL;
DROP TABLE IF  EXISTS PHONEBILL.CUSTOMER_ADDRESSES;
DROP TABLE IF  EXISTS PHONEBILL.BILL_DETAIL_LINES;
DROP TABLE IF  EXISTS PHONEBILL.CUSTOMER_PHONE_CALLS;
DROP TABLE IF  EXISTS PHONEBILL.BILL_HEADERS;
DROP TABLE IF  EXISTS PHONEBILL.CUSTOMER_PHONE_NUMBERS;
DROP TABLE IF  EXISTS PHONEBILL.CUSTOMER;
DROP TABLE IF  EXISTS PHONEBILL.REF_ADDRESS_TYPE;
DROP TABLE IF  EXISTS PHONEBILL.ADDRESSES;
DROP TABLE IF  EXISTS PHONEBILL.TARIFFS;
DROP TABLE IF  EXISTS  PHONEBILL.REF_TARIFF_TYPES;
DROP TABLE IF  EXISTS PHONEBILL.REF_NUMBER_CALLED_TYPE;
DROP TABLE IF  EXISTS PHONEBILL.REF_CUSTOMER_NUMBER_TYPES;

CREATE TABLE IF NOT EXISTS  PHONEBILL.ADDRESSES(
   ADDRESS_ID INT PRIMARY KEY AUTO_INCREMENT,
   LINE1 VARCHAR(20),
   LINE2 VARCHAR(20),
   LINE3 VARCHAR(20),
   CITY VARCHAR(20),
   ZIP_POSTCODE VARCHAR(20),
   STATE_PROVINCE_COUNTRY VARCHAR(20),
   COUNTRY VARCHAR(20),
   OTHER_DETAILS TEXT ASCII
) ENGINE = INNODB ROW_FORMAT = DEFAULT;



CREATE TABLE IF NOT EXISTS  PHONEBILL.REF_TARIFF_TYPES (
   TARIFF_TYPE_CODE INT PRIMARY KEY,
   TARIFF_TYPE_DESCRIPTION VARCHAR(20)
) ENGINE = INNODB ROW_FORMAT = DEFAULT;

CREATE TABLE IF NOT EXISTS PHONEBILL.REF_NUMBER_CALLED_TYPE (
   NUMBER_CALLED_TYPE_CODE INT PRIMARY KEY,
   NUMBER_CALLED_TYPE_DESC VARCHAR(20)
) ENGINE = INNODB ROW_FORMAT = DEFAULT;

CREATE TABLE IF NOT EXISTS PHONEBILL.REF_CUSTOMER_NUMBER_TYPES (
   CUSTOMER_NUMBER_TYPE_CODE INT PRIMARY KEY,
   NUMBER_TYPE_DESCRIPTION VARCHAR(20)
) ENGINE = INNODB ROW_FORMAT = DEFAULT;

CREATE TABLE IF NOT EXISTS  PHONEBILL.TARIFFS (
   TARIFF_ID INT PRIMARY KEY,
   TARIFF_TYPE_CODE INT,
   TARIFF_NAME VARCHAR(20),
   TARIFF_RATE INT,
   TARIFF_DATAILS VARCHAR(20),
    FOREIGN KEY (TARIFF_TYPE_CODE) REFERENCES REF_TARIFF_TYPES(TARIFF_TYPE_CODE) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE = INNODB ROW_FORMAT = DEFAULT;

CREATE TABLE IF NOT EXISTS PHONEBILL.CUSTOMER (
   CUSTOMER_ID INT PRIMARY KEY,
   CUSTOMER_NAME VARCHAR(20),
   CUSTOMER_EMAIL VARCHAR(100),
   CUSTOMER_ADDRESS VARCHAR(20),
   COMMERCIAL_OR_DOMAESTIC INT,
   OTHER_DETAILS VARCHAR(20)
) ENGINE = INNODB ROW_FORMAT = DEFAULT;

CREATE TABLE IF NOT EXISTS PHONEBILL.REF_ADDRESS_TYPE (
   ADDRESS_TYPE_CODE INT PRIMARY KEY,
   ADDRESS_TYPE_DESCRIPTION VARCHAR(20)
) ENGINE = INNODB ROW_FORMAT = DEFAULT;
CREATE TABLE IF NOT EXISTS PHONEBILL.CUSTOMER_PHONE_NUMBERS (
   CUSTOMER_PHONE_NUMBER VARCHAR(20) PRIMARY KEY,
   CUSTOMER_ID INT,
   NUMBER_TYPE_CODE INT,
   HELD_FROM_DATE DATE,
   HELD_TO_DATE DATE,
   OTHER_DETAILS VARCHAR(20),
   FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) ON UPDATE CASCADE ON DELETE RESTRICT,
   FOREIGN KEY (NUMBER_TYPE_CODE) REFERENCES REF_CUSTOMER_NUMBER_TYPES(CUSTOMER_NUMBER_TYPE_CODE) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE = INNODB ROW_FORMAT = DEFAULT;

CREATE TABLE IF NOT EXISTS PHONEBILL.BILL_HEADERS (
   BILL_HEADER_ID INT PRIMARY KEY,
   PHONE_NUMBER VARCHAR(20),
   BILL_ISSUE_DATE DATE,
   PAYMENT_DUE_DATE DATE,
   ORIGINAL_AMOUNT_DUE DOUBLE,
   AMOUNT_OUTSTANDING DOUBLE,
    FOREIGN KEY (PHONE_NUMBER) REFERENCES CUSTOMER_PHONE_NUMBERS(CUSTOMER_PHONE_NUMBER) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE = INNODB ROW_FORMAT = DEFAULT;

CREATE TABLE IF NOT EXISTS PHONEBILL.CUSTOMER_PHONE_CALLS (
   PHONE_CALL_ID INT PRIMARY KEY,
   CUSTOMER_PHONE_NUMBER VARCHAR(20),
   NUMBER_CALLED_TYPE_CODE INT,
   NUMBER_CALLED VARCHAR(20),
   CALL_START_DATETIME DATETIME,
   CALL_END_DATETIME DATETIME,
   OTHER_DETAILS VARCHAR(20),
   FOREIGN KEY (CUSTOMER_PHONE_NUMBER) REFERENCES CUSTOMER_PHONE_NUMBERS(CUSTOMER_PHONE_NUMBER) ON UPDATE CASCADE ON DELETE RESTRICT,
   FOREIGN KEY (NUMBER_CALLED_TYPE_CODE) REFERENCES REF_NUMBER_CALLED_TYPE(NUMBER_CALLED_TYPE_CODE) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE = INNODB ROW_FORMAT = DEFAULT;

CREATE TABLE PHONEBILL.BILL_DETAIL_LINES (
   BILL_DETAIL_LINE_ID INT PRIMARY KEY,
   BILL_HEADER_ID INT,
   PHONE_CALL_ID INT,
   TARIFF_ID INT,
   CALL_DURATION DOUBLE,
   CALL_COST DOUBLE,
   FOREIGN KEY (BILL_HEADER_ID) REFERENCES BILL_HEADERS(BILL_HEADER_ID) ON UPDATE CASCADE ON DELETE RESTRICT,
   FOREIGN KEY (PHONE_CALL_ID) REFERENCES CUSTOMER_PHONE_CALLS(PHONE_CALL_ID) ON UPDATE CASCADE ON DELETE RESTRICT,
   FOREIGN KEY (TARIFF_ID) REFERENCES TARIFFS(TARIFF_ID) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE = INNODB ROW_FORMAT = DEFAULT;

CREATE TABLE IF NOT EXISTS PHONEBILL.CUSTOMER_ADDRESSES (
   CUSTOMER_ADDRESS_ID INT PRIMARY KEY,
   ADDRESS_ID INT,
   ADDRESS_TYPE_CODE INT,
   CUSTOMER_ID INT,
   DATE_ADDRESS_FROM DATE,
   DATE_ADDRESS_TO DATE,
   FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESSES(ADDRESS_ID) ON UPDATE CASCADE ON DELETE RESTRICT,
   FOREIGN KEY (ADDRESS_TYPE_CODE) REFERENCES REF_ADDRESS_TYPE(ADDRESS_TYPE_CODE) ON UPDATE CASCADE ON DELETE RESTRICT,
   FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE = INNODB ROW_FORMAT = DEFAULT;

