/*
	-- SCRIPT DE BASE DE DATOS MYSQL 5.7
	-- ARQUITECTURA DE INFORMACIÓN
	-- PROYECTO 4, UNA 2018
	-- GERSON VARGAS & OSVALDO AGUERO
*/

/* ref_tariff_types */
INSERT INTO PHONEBILL.ref_tariff_types VALUES(1,'TariffType_01');
INSERT INTO PHONEBILL.ref_tariff_types VALUES(2,'TariffType_02');

/* Tariff */
INSERT INTO PHONEBILL.Tariffs VALUES(1,1,'Tariff_01',4,'Detail_01');
INSERT INTO PHONEBILL.Tariffs VALUES(2,2,'Tariff_02',5,'Detail_02');
INSERT INTO PHONEBILL.Tariffs VALUES(3,2,'Tariff_04',5,'Detail_02');
INSERT INTO PHONEBILL.Tariffs VALUES(4,2,'Tariff_05',5,'Detail_02');
INSERT INTO PHONEBILL.Tariffs VALUES(5,2,'Tariff_06',5,'Detail_02');
INSERT INTO PHONEBILL.Tariffs VALUES(6,2,'Tariff_07',5,'Detail_02');
INSERT INTO PHONEBILL.Tariffs VALUES(7,2,'Tariff_08',5,'Detail_02');

/* CUSTOMER */
INSERT INTO PHONEBILL.CUSTOMER VALUES(1,'Gerson','gerson@gmail.com','En la escuela',1,'First customer!');
INSERT INTO PHONEBILL.CUSTOMER VALUES(2,'Osvaldo','osvaldo@gmail.com','En la Universidad',1,'Second customer!');


INSERT INTO PHONEBILL.REF_ADDRESS_TYPE VALUES(1,'BILLING');
INSERT INTO PHONEBILL.REF_ADDRESS_TYPE VALUES(2,'RESIDENTIAL');


INSERT INTO  PHONEBILL.ADDRESSES VALUES(
   1,
   'LINE 1',
   'LINE 2',
   'LINE 3',
   'HEREDIA',
   '200534',
   'HEREDIA',
   'COSTA RICA',
   'NEXT TO THE POPS ICE CREAM SHOP');
INSERT INTO  PHONEBILL.ADDRESSES VALUES(
   2,
   'LINE 2',
   'LINE 2',
   'LINE 2',
   'SAN JOSE',
   '200534',
   'SAN JOSE',
   'COSTA RICA',
   'AT UNA LEFT HAND');
   
  INSERT INTO PHONEBILL.CUSTOMER_ADDRESSES VALUES(
   1,
   1,
   1,
   1,
   CURRENT_DATE,
   DATE_ADD(CURDATE(), INTERVAL 30 DAY));
   
     INSERT INTO PHONEBILL.CUSTOMER_ADDRESSES VALUES(
   2,
   2,
   2,
   2,
   CURRENT_DATE,
   DATE_ADD(CURDATE(), INTERVAL 30 YEAR));

/* ref_customer_number_types */
INSERT INTO ref_customer_number_types(CUSTOMER_NUMBER_TYPE_CODE,NUMBER_TYPE_DESCRIPTION)
VALUES(1,'NumberType_01');

INSERT INTO ref_customer_number_types(CUSTOMER_NUMBER_TYPE_CODE,NUMBER_TYPE_DESCRIPTION)
VALUES(2,'NumberType_02');

/* customer_phone_numbers */
INSERT INTO customer_phone_numbers(CUSTOMER_PHONE_NUMBER,CUSTOMER_ID,NUMBER_TYPE_CODE,HELD_FROM_DATE,HELD_TO_DATE,OTHER_DETAILS) VALUES(33667755,1,1,CURDATE(),CURDATE(),'detalles')
INSERT INTO customer_phone_numbers(CUSTOMER_PHONE_NUMBER,CUSTOMER_ID,NUMBER_TYPE_CODE,HELD_FROM_DATE,HELD_TO_DATE,OTHER_DETAILS) VALUES(88996655,2,1,CURDATE(),CURDATE(),'detalles2')

/* bill_headers */
INSERT INTO bill_headers(BILL_HEADER_ID,PHONE_NUMBER,BILL_ISSUE_DATE,PAYMENT_DUE_DATE,ORIGINAL_AMOUNT_DUE,AMOUNT_OUTSTANDING) VALUES(1,88996655,CURDATE(),CURDATE(),2,4)

/* bill_detail_lines */
insert into bill_detail_lines(BILL_DETAIL_LINE_ID,BILL_HEADER_ID,PHONE_CALL_ID,TARIFF_ID,CALL_DURATION,CALL_COST)VALUES(1,1,1,2,50,5)

INSERT INTO PHONEBILL.REF_NUMBER_CALLED_TYPE VALUES(
   1,
   'OVERSEAS');
INSERT INTO PHONEBILL.REF_NUMBER_CALLED_TYPE VALUES(
   2,
   '0800');
   INSERT INTO PHONEBILL.REF_NUMBER_CALLED_TYPE VALUES(
   3,
   '0900');
INSERT INTO PHONEBILL.CUSTOMER_PHONE_CALLS VALUES (
   1,
  '1',
   1,
   '2243434',
   CURDATE(),
   DATE_ADD(CURDATE(), INTERVAL 1 DAY),
   'Detalles de la llamada.');

commit;
 --- END ---

SELECT   BillDetail.BILL_DETAIL_LINE_ID,
	     Bill.BILL_HEADER_ID,
         PhoneNumber.CUSTOMER_PHONE_NUMBER,
         Tariff.TARIFF_ID,
         Tariff.TARIFF_NAME,
         BillDetail.CALL_DURATION,
         BillDetail.CALL_COST
		 FROM bill_detail_lines BillDetail 
         INNER JOIN bill_headers Bill
         	ON BillDetail.BILL_HEADER_ID = Bill.BILL_HEADER_ID
         INNER JOIN customer_phone_numbers PhoneNumber 
            ON Bill.PHONE_NUMBER = PhoneNumber.CUSTOMER_PHONE_NUMBER
         INNER JOIN tariffs Tariff 
            ON BillDetail.TARIFF_ID = Tariff.TARIFF_ID
WHERE BILL_DETAIL_LINE_ID = 1